apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mpiw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-mpiw@sha256:8265f1e4ae35bd4f7b9388fbd3f949948384689714fd6dc13ddb0a747fee6e1d
        name: my-nodejs
        resources: {}
status: {}
